### ISSUE TITLE
Dolfin build failure on Ubuntu 22.04

### ISSUE THREAD

**Issue by penelsonUMN** [TerraFERMA/TerraFERMA#49]
Hi,

I was able to successfully build TerraFERMA on Ubuntu 20.04 following the instructions in the wiki (https://github.com/TerraFERMA/TerraFERMA/wiki/Installation) however when following the same instructions on Ubuntu 22.04, I encounter an error running the cmake configuration command for the Dolfin build step.

`cmake -DCMAKE_BUILD_TYPE=Release \
      -DDOLFIN_ENABLE_CHOLMOD:BOOL=OFF \
      -DDOLFIN_ENABLE_UMFPACK:BOOL=OFF \
      -DDOLFIN_ENABLE_TRILINOS:BOOL=OFF \
      -DDOLFIN_ENABLE_SLEPC:BOOL=OFF  \
      -DMETIS_LIBRARY=${PETSC_DIR}/lib/libmetis.so \
      -DPARMETIS_INCLUDE_DIRS=${PETSC_DIR}/include \
      -DPARMETIS_LIBRARY=${PETSC_DIR}/lib/libparmetis.so \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
      ../.`

`CMake Error at CMakeLists.txt:626 (message):
  Generation of form files failed:

  Traceback (most recent call last):

    File "/home/penelson/terra/dolfin/cmake/scripts/generate-form-files.py", line 22, in <module>
      import ffc

  ModuleNotFoundError: No module named 'ffc' 

-- Configuring incomplete, errors occurred!
See also "/home/penelson/terra/dolfin/build/CMakeFiles/CMakeOutput.log".`

I have attached the CMakeOutput.log file as well as the outputted error for reference.
[CMakeOutput.log](https://github.com/user-attachments/files/16353253/CMakeOutput.log)
[dolfin_error.txt](https://github.com/user-attachments/files/16353265/dolfin_error.txt)

Is it possible to build for Ubuntu 22.04?

Thanks!

**Comment by cianwilson** [comment]
Hi @penelsonUMN , thanks for the issue report.

I'm trying out an installation on a clean 22.04 machine now but it might take me until tomorrow to get to finish that.  I don't think there should be any significant issues despite the instructions being for 20.04 but I'll update the instructions if anything comes up.

In the meantime I think your failure isn't because dolfin is failing but because ffc may have not been installed properly in an earlier step or your installation path hasn't been added to the PYTHONPATH correctly.  The current instructions tell you to update the PYTHONPATH but assume python 3.8 as that was the default with 20.04.  I wonder if the fix could just be changing that assumption to python 3.10 in the PYTHONPATH, e.g.
```
export PYTHONPATH=$PYTHONPATH:$INSTALL_PREFIX/lib/python3.10/site-packages
```

I'll try this myself once my test installation gets there.

Cheers,
Cian

**Comment by cianwilson** [comment]
Just a quick update that I've been able to reproduce the issue you were seeing @penelsonUMN .  The version of pip that ships with ubuntu 22.04 has changed the default installation path so the PYTHONPATH is indeed incorrect but not for the reason I was thinking.  I'm working on updating the installation instructions and will update this issue once I've finished.
Thanks!
Cian

**Comment by cianwilson** [comment]
Hi @penelsonUMN ,
I think I've updated the instructions to be inclusive of 22.04 now.

The main changes are that `PATH` and `PYTHONPATH` need to be set a little differently.  Additionally I'm restricting pip3 to not install dependencies as these sometimes conflict with the apt packages.  Additionally, I made some changes to dolfin to get it to compile with the 22.04 version of boost so you'll need to pull that again before recompiling.

All the changes should already be on the website.  Please let me know if it still doesn't work.
Cheers,
Cian

**Comment by penelsonUMN** [comment]
Hi @cianwilson ,

Thanks for looking into this - my apologies for the slow response, I was out of town. Your changes do appear to have worked! I am able to build on 22.04 now. I will let you know if something comes up but as it stands I believe this is resolved.

Thanks!
-Peter
